---
- name: "Install required dependencies"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - cups
    - git
- name: Add pi user to lp and lpadmin groups
  become: yes
  user:
    name: pi
    groups: lp,lpadmin
    append: yes
- name: Make cups listen on all interfaces
  become: yes
  lineinfile:
    path: /etc/cups/cupsd.conf
    regexp: '^Listen .*:631'
    line: 'Listen 0.0.0.0:631'
- name: Allow regular access
  become: yes
  replace:
    path: /etc/cups/cupsd.conf
    regexp: '^<Location />\n(  Allow all\n)?'
    replace: '<Location />\n  Allow all\n'
- name: Allow admin access
  become: yes
  replace:
    path: /etc/cups/cupsd.conf
    regexp: '^<Location /admin>\n(  Allow all\n)?'
    replace: '<Location /admin>\n  Allow all\n'
- name: Enable cups
  become: yes
  systemd:
    name: cups
    enabled: true
    state: restarted