---
- name: "Install necessary packages"
  become: true
  hosts: all
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: "Install vim"
      apt:
        name: vim
        state: present
- name: "Install and configure CUPS"
  hosts: all
  tags: [cups]
  roles:
    - role: cups
- name: "Enable ssh"
  hosts: all
  tags: [systemd]
  tasks:
    - name: Enable ssh
      become: true
      systemd:
        name: ssh
        enabled: yes

