---
- name: "Install necessary packages"
  become: true
  hosts: all
  tags: [update-system]
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: "Install vim"
      apt:
        name: vim
        state: present
- name: "Set hostname"
  hosts: all
  tags: [hostname,systemd]
  tasks:
    - name: Set hostname
      become: true
      hostname:
        use: debian
        name: pi-print-server
- name: "Install and configure CUPS"
  hosts: all
  tags: [cups]
  roles:
    - role: cups